config/routes.rb
Rails.application.routes.draw do
  

  resources :forecasts
  root :to => "player_rounds#index"
  
  resources :player_rounds

  resources :rounds do
  	resources :player_rounds
  end

  resources :players do
  	resources :player_rounds
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player_round.rb
class PlayerRound < ApplicationRecord
	belongs_to :player
	belongs_to :round
end

app/controllers/player_rounds_controller.rb
class PlayerRoundsController < ApplicationController
  before_action :set_player_round, only: [:show, :edit, :update, :destroy]

  # GET /player_rounds
  # GET /player_rounds.json
  def index
    @players = Player.all
    @player_rounds = PlayerRound.all
    @rounds = Round.all

    @forecast = Forecast.new({
      :lat => -33.3444,
      :lng => -70.8577
      })
    
    @weather = @forecast.get_weather_data
    @daily_weather = @weather.daily.data.first(7)

    @daysName = Array.new
    @tempMaxs = Array.new

    @daily_weather.each do |day|
      @daysName << Time.at(day.time).strftime('%A')
      
      @tempMaxs << fahrToCel(day.apparentTemperatureMax)
    end    
  end

  # GET /player_rounds/1
  # GET /player_rounds/1.json
  def show
  end

  # GET /player_rounds/new
  def new
    @round = Round.find(params[:round_id])
    @player_round = PlayerRound.new()
  end

  # GET /player_rounds/1/edit
  def edit
  end

  # POST /player_rounds
  # POST /player_rounds.json
  def create

    for player in Player.all do

      @player = player      
      @round = Round.find(params[:round_id])

      @amount = amountBet(player.money, @round.conservative)

      @betValue = resultBet

      @player_round = PlayerRound.new({
        :amount => @amount,
        :round => @round,
        :player => @player,
        :betValue => @betValue
      })    

      puts @round.conservative

      if @player_round.save()
        varAux = true
      else
        varAux = false
      end
    end

    if varAux
      redirect_to @round, notice => "La apuesta ha sido agregada"      
    else
      redirect_to @round, notice => "La apuesta NO ha sido agregada"      
    end    
  end

  # PATCH/PUT /player_rounds/1
  # PATCH/PUT /player_rounds/1.json
  def update
    respond_to do |format|
      if @player_round.update(player_round_params)
        format.html { redirect_to @player_round, notice: 'Player round was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_round }
      else
        format.html { render :edit }
        format.json { render json: @player_round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_rounds/1
  # DELETE /player_rounds/1.json
  def destroy
    @player_round.destroy
    respond_to do |format|
      format.html { redirect_to player_rounds_url, notice: 'Player round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def resultBet
    
    prob = Random.new.rand(1..100)
    result = ""

    puts prob

    if prob <= 2
      result = "Verde"
    elsif prob >= 3 and prob <= 51
      result = "Rojo"
    else
      result = "Negro"
    end
        
    return result
  end

  def amountBet(money, conservative)

    puts "money es:"
    puts money

    betMoney = 0

    if(conservative)
      prob = Random.new.rand(4..10)      
    else
      prob = Random.new.rand(8..15)
    end

    prob = (prob * 1.0) / 100    

    if money < 1000 and money != 0
      betMoney = money
    elsif money != 0
      betMoney = money * prob
    end
      
    betMoney = betMoney.to_i
    puts betMoney

    return betMoney          

  end

  def fahrToCel(temp)
    tempCelsius = temp - 32
    tempCelsius = tempCelsius*5
    tempCelsius = tempCelsius/9
    tempCelsius = '%.0f' % tempCelsius
    return tempCelsius
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_round
      @player_round = PlayerRound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_round_params
      params.require(:player_round).permit(:amount)
    end
end

app/helpers/player_rounds_helper.rb
module PlayerRoundsHelper
end

app/views/player_rounds/_form.html.erb
<%= form_with(model: player_round, local: true) do |form| %>
  <% if player_round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player_round.errors.count, "error") %> prohibited this player_round from being saved:</h2>

      <ul>
      <% player_round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :player_round_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/player_rounds/_form_save_player_round.html.erb
<%= form_for([@round, @player_round]) do |f| %>
   <% if @player_round.errors.any? %>
      <ul>
         <% @player_round.errors.each do |atributo, mensaje| %>
         <li> <%= mensaje %> </li>
         <% end %>
      </ul>
   <% end %>   
   <%= f.submit "Enviar" %> <%= link_to "Volver", @round %>
<% end %>

app/views/player_rounds/edit.html.erb
<h1>Editing Player Round</h1>

<%= render 'form', player_round: @player_round %>

<%= link_to 'Show', @player_round %> |
<%= link_to 'Back', player_rounds_path %>

app/views/player_rounds/index.html.erb
<p id="notice"><%= notice %></p>


  <div class="row">
    <h1 class="text-center">Juego de la Ruleta</h1>
  </div>
    
  <div class="row">
    <div class="col-md-8">
      <h2 class="text-center"> Rondas </h2>

      <% count = 0 %>

      <% @rounds.each do |round| %>
        
        
        <% count = count + 1 %>
        <% textAux = "NO" %>
        <% if round.conservative %>
        <% textAux = "SI" %>
        <% end %>

        <div class="panel panel-default">
          <div class="panel-heading">
            <th>Ronda  <%=count %></th>
          </div>
          
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Resultado ruleta</th>
                <th>Fecha y Hora</th>
                <th>Pronostico de temperatura mayor a 25°</th>
              </tr>
            </thead>  
            <tbody>
              <tr>
                <td> <%= round.result %> </td>
                <td> <%= round.dateTime %> </td>
                <td> <%= textAux %> </td>
              </tr>
            </tbody>
          </table>
        
          <hr class="separetor-table">

          <table class="table table-hover">
            <thead>
              <tr>
                <th>Nombre Jugador</th>
                <th>Cantidad apostada </th>
                <th>Color apostado </th>
              </tr>
            </thead>
            <tbody>

            <% @player_rounds.each do |player_round| %>
              <% if player_round.round.id == round.id %>
                
                <tr>
                  <td> <%= player_round.player.name  %> </td>
                  <td> <%= player_round.amount  %> </td>
                  <td> <%= player_round.betValue  %> </td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
              
        </div>
      <% end %>

      <% if count == 0 %>
        <h3 class="text-center" style="margin-top: 200px;"><%= "Aún no existen rondas" %></h3>
      <% end %>

    </div>

    <div class="col-md-4">
      <div class="row">
        <h2 class="text-center">Jugadores</h2>
        
        <table class="table table-hover">
            <thead>
              <tr>
                <th>Nombre Jugador</th>
                <th>Dinero actual </th>                
              </tr>
            </thead>
            <tbody>

            <% @players.each do |player| %>              
                <tr>
                  <td> <%= player.name  %> </td>
                  <td> <%= player.money  %> </td>                  
                </tr>              
            <% end %>
            </tbody>
          </table>

        <div class="text-center">
          <%= link_to 'Ir a Panel de Jugadores', players_path %>
        </div>

      </div>
      <div class="row">
        <h2 class="text-center">Pronostico del tiempo</h2>
      
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Día</th>
              <th>Temperatura Máxima </th>                
            </tr>
          </thead>
          <tbody>

          <% for i in (0..6) %>
              <tr>
                <td> <%= @daysName[i]%> </td>
                <td> <%= @tempMaxs[i]%>°C </td>                  
              </tr>              
          <% end %>
          </tbody>
        </table>
      </div>


    </div>
    <%= link_to 'Nueva Ronda', new_round_path %>
  </div>

  <br>

  

app/views/player_rounds/new.html.erb
<h1>New Player Round</h1>

<%= render :partial => "form_save_player_round" %>

app/views/player_rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @player_round.amount %>
</p>

<%= link_to 'Edit', edit_player_round_path(@player_round) %> |
<%= link_to 'Back', player_rounds_path %>