config/routes.rb
Rails.application.routes.draw do
  

  resources :forecasts
  root :to => "player_rounds#index"
  
  resources :player_rounds

  resources :rounds do
  	resources :player_rounds
  end

  resources :players do
  	resources :player_rounds
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/round.rb
class Round < ApplicationRecord
	has_and_belongs_to_many :players
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @round = Round.find(params[:id])
    @player_rounds = PlayerRound.select("id, amount, betValue, player_id, round_id").where(:round_id => params[:id])
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new()
    

    @dateTime = Time.new
    @conservative = isConservative
    @result = resultRulleteBet

    @round.dateTime = @dateTime
    @round.conservative = @conservative
    @round.result = @result

    
    if @round.save      
      addPlayerRound(@round.id)
    else
      format.html { render :new }
      format.json { render json: @round.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def isConservative

    tempHigh = false

    @forecast = Forecast.new({
      :lat => -33.4569400,
      :lng => -70.6482700
      })
    
    @weather = @forecast.get_weather_data       
    @current_weather = @weather.currently
    @daily_weather = @weather.daily.data.first(7)

    @tempCelsius = 0

    @daily_weather.each do |day|                  
      
      tempCelsius = fahrToCel(day.apparentTemperatureMax)

      puts 'temperatura es '
      puts tempCelsius

      if tempCelsius >= 25
        tempHigh = true
      end
    end

    return tempHigh
  end


  def addPlayerRound(round_id)

    for player in Player.all do
      
      @player = player      
      @round = Round.find(round_id)
    
      @amount = amountBet(player.money, @round.conservative)
      @betValue = "NO APUESTA"

      if @amount != 0        
        @betValue = resultRulleteBet
      end
      
      @player_round = PlayerRound.new({
        :amount => @amount,
        :round => @round,
        :player => @player,
        :betValue => @betValue
      })    

      if @player_round.save()
        varAux = true
        playRound(@amount, @betValue, @round.result, @player)
      else
        varAux = false
      end
    end

    if varAux
      redirect_to @round, notice => "La apuesta ha sido agregada"      
    else
      redirect_to @round, notice => "La apuesta NO ha sido agregada"      
    end

  end

  def playRound(amount, betValue, result, player)  

    amountWon = amount * -1
    
    if betValue == result

      if betValue == 'Verde'
        amountWon = amountWon + (amount*15)
      elsif betValue == 'Rojo' or betValue == 'Negro'
        amountWon = amountWon + (amount*2)
      else
        puts 'Error en colores'        
      end        
    end    
    
    newMoney = amountWon + player.money

    player.money = newMoney
    player.save()
  end


  def amountBet(money, conservative)

    betMoney = 0

    if(conservative)
      prob = Random.new.rand(4..10)      
    else
      prob = Random.new.rand(8..15)
    end

    prob = (prob * 1.0) / 100    

    if money < 1000 and money != 0
      betMoney = money
    elsif money != 0
      betMoney = money * prob
    end
      
    betMoney = betMoney.to_i
    puts betMoney

    return betMoney          

  end

  def resultRulleteBet

    
    prob = Random.new.rand(1..100)
    result = ""

    puts prob

    if prob <= 2
      result = "Verde"
    elsif prob >= 3 and prob <= 51
      result = "Rojo"
    else
      result = "Negro"
    end
        
    return result
  end

  def fahrToCel(temp)
      tempCelsius = temp - 32
      tempCelsius = tempCelsius*5
      tempCelsius = tempCelsius/9
      tempCelsius = '%.0f' % tempCelsius
      return tempCelsius
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:number)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_with(model: round, local: true) do |form| %>
  <% if round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rounds</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Datetime</th>
      <th>Conservative</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.id %></td>
        <td><%= round.dateTime %></td>
        <td><%= round.conservative %></td>
        <td><%= round.result %></td>
        <td><%= link_to 'Show', round %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path %>

app/views/rounds/new.html.erb
<h1>New Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @round.id %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @round.dateTime %>
</p>

<p>
  <strong>Conservative:</strong>
  <%= @round.conservative %>
</p>

<p>
  <strong>Result:</strong>
  <%= @round.result %>
</p>


<p> <%= link_to "Agregar una apuesta", new_round_player_round_path(@round) %> | <%= link_to "Volver", rounds_path %> </p>
<hr />
<ul style="list-style: none; padding: 0px;">
	<h3>Apuestas </h3>
   <% @player_rounds.each do |player_round| %>   
   <li>

      <div> <%= player_round.amount %> </div>
      <div> <%= player_round.betValue %> </div>
      <div> <%= player_round.id %> </div>
      <div> <%= player_round.player.name %> </div>
      <p> 
         <%= link_to "Editar", edit_round_player_round_path(@round, player_round) %>
         | 
         <%= link_to "Eliminar", round_player_round_path(@round, player_round), :confirm => "Seguro desea eliminar este comentario?", :method => :delete %> 
         </p>
         <hr />
   </li>
 <% end %>
</ul>


<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>