config/routes.rb
Rails.application.routes.draw do
  

  resources :forecasts
  root :to => "player_rounds#index"
  
  resources :player_rounds

  resources :rounds do
  	resources :player_rounds
  end

  resources :players do
  	resources :player_rounds
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forecast.rb
class Forecast < ApplicationRecord

	def get_weather_data
		ForecastIO.forecast(lat,lng)
	end
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: [:show, :edit, :update, :destroy]

  # GET /forecasts
  # GET /forecasts.json
  def index
    @forecasts = Forecast.all
  end

  # GET /forecasts/1
  # GET /forecasts/1.json
  def show
    def show       
      @weather = @forecast.get_weather_data       
      @current_weather = @weather.currently
      @daily_weather = @weather.daily.data.first(7)  
end
  end

  # GET /forecasts/new
  def new
    @forecast = Forecast.new
  end

  # GET /forecasts/1/edit
  def edit
  end

  # POST /forecasts
  # POST /forecasts.json
  def create
    @forecast = Forecast.new(forecast_params)

    respond_to do |format|
      if @forecast.save
        format.html { redirect_to @forecast, notice: 'Forecast was successfully created.' }
        format.json { render :show, status: :created, location: @forecast }
      else
        format.html { render :new }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forecasts/1
  # PATCH/PUT /forecasts/1.json
  def update
    respond_to do |format|
      if @forecast.update(forecast_params)
        format.html { redirect_to @forecast, notice: 'Forecast was successfully updated.' }
        format.json { render :show, status: :ok, location: @forecast }
      else
        format.html { render :edit }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forecasts/1
  # DELETE /forecasts/1.json
  def destroy
    @forecast.destroy
    respond_to do |format|
      format.html { redirect_to forecasts_url, notice: 'Forecast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forecast_params
      params.require(:forecast).permit(:lat, :lng)
    end
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_form.html.erb
<%= form_with(model: forecast, local: true) do |form| %>
  <% if forecast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
      <% forecast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat, id: :forecast_lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng, id: :forecast_lng %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forecasts/edit.html.erb
<h1>Editing Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Show', @forecast %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forecasts</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forecasts.each do |forecast| %>
      <tr>
        <td><%= forecast.lat %></td>
        <td><%= forecast.lng %></td>
        <td><%= link_to 'Show', forecast %></td>
        <td><%= link_to 'Edit', edit_forecast_path(forecast) %></td>
        <td><%= link_to 'Destroy', forecast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forecast', new_forecast_path %>

app/views/forecasts/new.html.erb
<h1>New Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @forecast.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @forecast.lng %>
</p>


<h3> The weather is <%= @current_weather.summary %> and <%= @current_weather.temperature %>
</h3>

<% @daily_weather.each do |day| %> 
	<%= Time.at(day.time).strftime('%A') %>

  	<%= day.summary %><br>
    	High: <%= day.apparentTemperatureMax %> | Low: <%= day.apparentTemperatureMin %>
<% end %>

<%= link_to 'Edit', edit_forecast_path(@forecast) %> |
<%= link_to 'Back', forecasts_path %>